services:
  frontend:
    image: registry.digitalocean.com/clickplanet-frontend/frontend:latest
    ports:
      - "443:443"
    volumes:
      - type: bind
        source: ./tls/fullchain.pem
        target: /etc/letsencrypt/live/clickplanet.lol/fullchain.pem
      - type: bind
        source: ./tls/privkey.pem
        target: /etc/letsencrypt/live/clickplanet.lol/privkey.pem
      - type: bind
        source: ./nginx/prod.conf
        target: /etc/nginx/conf.d/nginx.conf